In [6]:
import numpy as np

In [33]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [31]:
a[::-1]

array([3, 2, 1])

In [14]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
np.zeros((4, 2), dtype=np.int32)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [10]:
np.arange(3,7)

array([3, 4, 5, 6])

In [11]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
np.random.rand(2,4)

array([[0.22199968, 0.26572991, 0.05196897, 0.57123707],
       [0.68516717, 0.37213148, 0.48806053, 0.43835465]])

In [16]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
# 输出 32 (1*4 + 2*5 + 3*6)
np.dot(a, b)

32

In [29]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
"""
进行矩阵乘法操作
矩阵 a 乘以矩阵 b 的结果会是一个新的 2x2 矩阵。
对应位置的元素相乘再相加：
第一行第一列元素：1∗5+2∗7=19
第一行第二列元素：1∗6+2∗8=22
第二行第一列元素：3∗5+4∗7=43
第二行第二列元素：3∗6+4∗8=50
"""
a @ b

array([[19, 22],
       [43, 50]])

In [34]:
from PIL import Image

In [35]:
im = Image.open('F:/image/bus.jpg')
im.show()

In [36]:
im = np.array(im)
im.shape

(1080, 810, 3)

In [37]:
im[100,100]

array([210, 189, 158], dtype=uint8)

In [40]:
im_r=im[:,:,0]
Image.fromarray(im_r).show()

In [41]:
im1 = np.array(Image.open('F:/image/bus.jpg'))
im2 = np.array(Image.open('F:/image/zidane.jpg'))
im_blend = im1 * 0.4 + im2 * 0.6
im_blend = im_blend.astype(np.uint8)
Image.fromarray(im_blend).show()

ValueError: operands could not be broadcast together with shapes (1080,810,3) (720,1280,3) 